### ISSUE TITLE
EOFerror when running damMer_tracks.py

### ISSUE THREAD

**Issue by hacaoe** [robertkrautz/NanoDam_analysis#1]
Hi Robert,

I am currently trying to analyse DamID data and was trying to run the damMer_tracks.py script to get the peaks after getting the bedgraphs for the samples. When running the script, I get an error like this
Traceback (most recent call last):
  File "PotentialTranscriptionFactors/CREBb/CrebBDamID/NonTrained/NanoDam_analysis/damMer_tracks.py", line 718, in <module>
    main()
  File "PotentialTranscriptionFactors/CREBb/CrebBDamID/NonTrained/NanoDam_analysis/damMer_tracks.py", line 598, in main
    bwuse = checkt(args.bgToBw)
  File "PotentialTranscriptionFactors/CREBb/CrebBDamID/NonTrained/NanoDam_analysis/damMer_tracks.py", line 150, in checkt
    desc = input('Use: [1 - ' + tcho + '] or [2 - ' + tdet + ']?\n')
EOFError: EOF when reading a line

Best,
Hasan

**Comment by hacaoe** [comment]
Ah, I was able to solve the issue (was an issue on my side having 2 usable bedgraphtobigwigs executables, which created the issue). The script is running now, but it's running for very long. How long should an analysis with 3 comparisons take for damMer_tracks.py take?
